// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBlockchain.Infrastructure.Data;

#nullable disable

namespace MyBlockchain.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250927111031_eth_block_tbl_create")]
    partial class eth_block_tbl_create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("MyBlockchain.Domain.Entities.EthBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BaseFee")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HighGasPrice")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HighPriorityFee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastForkHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastForkHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LatestUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LowGasPrice")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LowPriorityFee")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediumGasPrice")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MediumPriorityFee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PeerCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnconfirmedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EthBlocks", (string)null);
                });

            modelBuilder.Entity("MyBlockchain.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
